name: Auto Build Executable File

on:
  push:
    branches:
      - master
      - hlw
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Build_windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python #安装python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
      - name: Install requirements #安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build EXE
        run: |
          pyinstaller -F youtubedl_vimeo.py -n vimeo_downloader
      - name: Upload EXE
        uses: actions/upload-artifact@v2.2.2
        with:
          name: vimeo_downloader_windows
          path: dist/*
  Build_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python #安装python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8
      - name: Install requirements #安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build Executable File
        run: |
          pyinstaller -F youtubedl_vimeo.py -n vimeo_downloader
      - name: Upload File
        uses: actions/upload-artifact@v2.2.2
        with:
          name: vimeo_downloader_linux
          path: dist/*

